"use client";

import * as React from "react";
import { SparkIcon } from "./icons";

type DNA = {
  available: boolean;
  dna?: string;
  brands?: string[];
  uses?: string[];
};

/**
 * Brand DNA: the brands and placements a track naturally fits. The lyric context
 * comes from Musixmatch (short, live, never stored); the recommendation is
 * generated by the AI model. Self-hides when unavailable.
 */
export function BrandDNACard({
  trackId,
  title,
  artist,
  genre,
}: {
  trackId: string;
  title: string;
  artist: string;
  genre?: string;
}) {
  const [data, setData] = React.useState<DNA | null>(null);
  const [done, setDone] = React.useState(false);

  React.useEffect(() => {
    let active = true;
    fetch("/api/brand-dna", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ trackId, title, artist, genre }),
    })
      .then((r) => r.json())
      .then((d: DNA) => {
        if (!active) return;
        setData(d);
        setDone(true);
      })
      .catch(() => active && setDone(true));
    return () => {
      active = false;
    };
  }, [trackId, title, artist, genre]);

  if (!done) {
    return (
      <div className="sf-card sf-card-pad">
        <div className="h-4 w-32 animate-pulse rounded bg-ink-700/50" />
        <div className="mt-3 h-3 w-full animate-pulse rounded bg-ink-700/40" />
        <div className="mt-3 flex gap-1.5">
          {Array.from({ length: 4 }).map((_, i) => (
            <div key={i} className="h-6 w-16 animate-pulse rounded-full bg-ink-700/40" />
          ))}
        </div>
      </div>
    );
  }

  if (!data?.available) return null;

  const brands = data.brands ?? [];
  const uses = data.uses ?? [];

  return (
    <div className="sf-card sf-card-pad">
      <div className="mb-3 flex items-center gap-2">
        <SparkIcon className="h-5 w-5 text-lime-400" aria-hidden />
        <h3 className="text-sm font-semibold text-white">Brand DNA</h3>
      </div>

      {data.dna && (
        <p className="text-sm leading-relaxed text-soft">{data.dna}</p>
      )}

      {brands.length > 0 && (
        <div className="mt-4">
          <p className="sf-eyebrow mb-2">Fits brands like</p>
          <div className="flex flex-wrap gap-1.5">
            {brands.map((b, i) => (
              <span
                key={i}
                className="rounded-full bg-purple-600/15 px-3 py-1 text-xs font-medium text-purple-100 ring-1 ring-inset ring-purple-500/25"
              >
                {b}
              </span>
            ))}
          </div>
        </div>
      )}

      {uses.length > 0 && (
        <div className="mt-4">
          <p className="sf-eyebrow mb-2">Works for</p>
          <div className="flex flex-wrap gap-1.5">
            {uses.map((u, i) => (
              <span
                key={i}
                className="rounded-full bg-lime-500/10 px-3 py-1 text-xs font-medium text-lime-300 ring-1 ring-inset ring-lime-500/25"
              >
                {u}
              </span>
            ))}
          </div>
        </div>
      )}

      <p className="mt-4 text-[11px] text-soft">
        Inferred from the track&apos;s theme &amp; metadata by AI — a creative
        starting point for pitching, not an endorsement.
      </p>
    </div>
  );
}
