"use client";

import * as React from "react";

export function GenerateBannerButton({
  reportId,
  initialBannerUrl,
}: {
  reportId: string;
  initialBannerUrl?: string;
}) {
  const [bannerUrl, setBannerUrl] = React.useState<string | undefined>(initialBannerUrl);
  const [loading, setLoading] = React.useState(false);
  const [error, setError] = React.useState<string | null>(null);

  async function generate() {
    if (loading) return;
    setError(null);
    setLoading(true);
    try {
      const res = await fetch("/api/banner", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ reportId }),
      });
      const data = await res.json().catch(() => ({}));
      if (!res.ok) {
        setError(data.error ?? "Banner generation failed.");
        return;
      }
      setBannerUrl(data.bannerUrl);
    } catch {
      setError("Network error — try again.");
    } finally {
      setLoading(false);
    }
  }

  if (bannerUrl) {
    return (
      <div className="overflow-hidden rounded-2xl border border-white/10">
        {/* eslint-disable-next-line @next/next/no-img-element */}
        <img
          src={bannerUrl}
          alt="Campaign banner"
          className="aspect-[16/6] w-full object-cover"
          referrerPolicy="no-referrer"
        />
        <div className="flex items-center justify-between bg-white/[0.02] px-4 py-2.5">
          <div className="flex items-center gap-2">
            <span className="h-1.5 w-1.5 rounded-full bg-lime-400" />
            <p className="text-xs text-soft">Campaign banner generated by Higgsfield</p>
          </div>
          <span className="rounded-full bg-lime-400/10 px-2 py-0.5 text-[10px] font-semibold text-lime-300 ring-1 ring-inset ring-lime-400/20">
            Ready to pitch
          </span>
        </div>
      </div>
    );
  }

  return (
    <div className="sf-card sf-card-pad">
      <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
        <div className="min-w-0">
          <p className="text-sm font-semibold text-white">Campaign Banner</p>
          <p className="mt-0.5 text-xs text-soft">
            Generate a Higgsfield AI banner tailored to this brand, brief, and audience. One per report.
          </p>
        </div>
        <button
          type="button"
          onClick={generate}
          disabled={loading}
          className="inline-flex shrink-0 items-center gap-2 rounded-full bg-gradient-to-r from-purple-600 to-lime-500 px-4 py-2 text-sm font-semibold text-white shadow-md transition hover:opacity-90 active:scale-95 disabled:cursor-not-allowed disabled:opacity-60"
        >
          {loading ? (
            <>
              <Spinner className="h-4 w-4" />
              Generating…
            </>
          ) : (
            <>
              <ImageSparkIcon className="h-4 w-4" />
              Generate banner
            </>
          )}
        </button>
      </div>
      {loading && (
        <div className="mt-3 flex items-center gap-2 rounded-xl border border-purple-500/20 bg-purple-500/5 px-3 py-2">
          <Spinner className="h-3.5 w-3.5 text-purple-300" />
          <p className="text-xs text-purple-200">
            Higgsfield is crafting your campaign visual — this takes 20–40 s…
          </p>
        </div>
      )}
      {error && (
        <p role="alert" className="mt-2 text-xs text-red-300">
          {error}
        </p>
      )}
    </div>
  );
}

function Spinner({ className }: { className?: string }) {
  return (
    <svg viewBox="0 0 24 24" className={(className ?? "h-4 w-4") + " animate-spin"} fill="none" aria-hidden>
      <circle cx="12" cy="12" r="9" stroke="currentColor" strokeOpacity="0.25" strokeWidth="3" />
      <path d="M21 12a9 9 0 0 0-9-9" stroke="currentColor" strokeWidth="3" strokeLinecap="round" />
    </svg>
  );
}

function ImageSparkIcon({ className }: { className?: string }) {
  return (
    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={1.8} strokeLinecap="round" strokeLinejoin="round" className={className ?? "h-4 w-4"} aria-hidden>
      <rect x="3" y="3" width="18" height="18" rx="3" />
      <circle cx="8.5" cy="8.5" r="1.5" />
      <path d="m21 15-5-5L5 21" />
      <path d="m17 3 1.5 3L22 7.5 18.5 9 17 12l-1.5-3L12 7.5 15.5 6z" />
    </svg>
  );
}
