"use client";

import * as React from "react";

export function GenerateBannerButton({
  reportId,
  initialBannerUrl,
  compact = false,
}: {
  reportId: string;
  initialBannerUrl?: string;
  compact?: boolean;
}) {
  const [bannerUrl, setBannerUrl] = React.useState<string | undefined>(initialBannerUrl);
  const [loading, setLoading] = React.useState(false);
  const [error, setError] = React.useState<string | null>(null);

  async function generate() {
    if (loading) return;
    setError(null);
    setLoading(true);
    try {
      const res = await fetch("/api/banner", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ reportId }),
      });
      const data = await res.json().catch(() => ({}));
      if (!res.ok) {
        setError(data.error ?? "Banner generation failed.");
        return;
      }
      setBannerUrl(data.bannerUrl);
    } catch {
      setError("Network error — try again.");
    } finally {
      setLoading(false);
    }
  }

  /* ── COMPACT MODE (top action bar) ─────────────────────────── */
  if (compact) {
    if (bannerUrl) {
      return (
        <span className="inline-flex items-center gap-1.5 rounded-lg border border-lime-400/30 bg-lime-400/10 px-3 py-2 text-[13px] font-semibold text-lime-300">
          <CheckIcon className="h-4 w-4" />
          Banner ready
        </span>
      );
    }
    return (
      <div className="flex flex-col items-start gap-1">
        <button
          type="button"
          onClick={generate}
          disabled={loading}
          className={
            "inline-flex items-center gap-1.5 rounded-lg px-3.5 py-2 text-[13px] font-semibold transition disabled:cursor-not-allowed disabled:opacity-60 " +
            (error
              ? "bg-red-500/10 text-red-300 ring-1 ring-inset ring-red-500/30 hover:bg-red-500/20"
              : "bg-gradient-to-r from-purple-600 to-lime-500 text-white shadow-sm hover:opacity-90 active:scale-95")
          }
        >
          {loading ? (
            <>
              <Spinner className="h-4 w-4" />
              Generating…
            </>
          ) : error ? (
            <>
              <WarningIcon className="h-4 w-4" />
              Retry banner
            </>
          ) : (
            <>
              <ImageSparkIcon className="h-4 w-4" />
              Generate banner
            </>
          )}
        </button>
      </div>
    );
  }

  /* ── FULL MODE (standalone card below ReportCard — kept for backwards-compat) ── */
  if (bannerUrl) {
    return (
      <div className="overflow-hidden rounded-2xl border border-white/10">
        {/* eslint-disable-next-line @next/next/no-img-element */}
        <img
          src={bannerUrl}
          alt="Campaign banner"
          className="aspect-[16/6] w-full object-cover"
          referrerPolicy="no-referrer"
        />
        <div className="flex items-center justify-between bg-white/[0.02] px-4 py-2.5">
          <div className="flex items-center gap-2">
            <span className="h-1.5 w-1.5 rounded-full bg-lime-400" />
            <p className="text-xs text-soft">Campaign banner generated by Higgsfield</p>
          </div>
          <span className="rounded-full bg-lime-400/10 px-2 py-0.5 text-[10px] font-semibold text-lime-300 ring-1 ring-inset ring-lime-400/20">
            Ready to pitch
          </span>
        </div>
      </div>
    );
  }

  return (
    <div className="sf-card sf-card-pad">
      <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
        <div className="min-w-0">
          <p className="text-sm font-semibold text-white">Campaign Banner</p>
          <p className="mt-0.5 text-xs text-soft">
            Generate a Higgsfield AI banner tailored to this brand, brief, and audience. One per report.
          </p>
        </div>
        <button
          type="button"
          onClick={generate}
          disabled={loading}
          className="inline-flex shrink-0 items-center gap-2 rounded-full bg-gradient-to-r from-purple-600 to-lime-500 px-4 py-2 text-sm font-semibold text-white shadow-md transition hover:opacity-90 active:scale-95 disabled:cursor-not-allowed disabled:opacity-60"
        >
          {loading ? (
            <>
              <Spinner className="h-4 w-4" />
              Generating…
            </>
          ) : (
            <>
              <ImageSparkIcon className="h-4 w-4" />
              Generate banner
            </>
          )}
        </button>
      </div>
      {loading && (
        <div className="mt-3 flex items-center gap-2 rounded-xl border border-purple-500/20 bg-purple-500/5 px-3 py-2">
          <Spinner className="h-3.5 w-3.5 text-purple-300" />
          <p className="text-xs text-purple-200">
            Higgsfield is crafting your campaign visual — this takes 20–40 s…
          </p>
        </div>
      )}
      {error && (
        <p role="alert" className="mt-2 text-xs text-red-300">
          {error}
        </p>
      )}
    </div>
  );
}

function Spinner({ className }: { className?: string }) {
  return (
    <svg
      viewBox="0 0 24 24"
      className={(className ?? "h-4 w-4") + " animate-spin"}
      fill="none"
      aria-hidden
    >
      <circle cx="12" cy="12" r="9" stroke="currentColor" strokeOpacity="0.25" strokeWidth="3" />
      <path d="M21 12a9 9 0 0 0-9-9" stroke="currentColor" strokeWidth="3" strokeLinecap="round" />
    </svg>
  );
}

function ImageSparkIcon({ className }: { className?: string }) {
  return (
    <svg
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth={1.8}
      strokeLinecap="round"
      strokeLinejoin="round"
      className={className ?? "h-4 w-4"}
      aria-hidden
    >
      <rect x="3" y="3" width="18" height="18" rx="3" />
      <circle cx="8.5" cy="8.5" r="1.5" />
      <path d="m21 15-5-5L5 21" />
      <path d="m17 3 1.5 3L22 7.5 18.5 9 17 12l-1.5-3L12 7.5 15.5 6z" />
    </svg>
  );
}

function CheckIcon({ className }: { className?: string }) {
  return (
    <svg
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth={2.2}
      strokeLinecap="round"
      strokeLinejoin="round"
      className={className ?? "h-4 w-4"}
      aria-hidden
    >
      <polyline points="20 6 9 17 4 12" />
    </svg>
  );
}

function WarningIcon({ className }: { className?: string }) {
  return (
    <svg
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth={1.8}
      strokeLinecap="round"
      strokeLinejoin="round"
      className={className ?? "h-4 w-4"}
      aria-hidden
    >
      <path d="M10.29 3.86 1.82 18a2 2 0 0 0 1.71 3h16.94a2 2 0 0 0 1.71-3L13.71 3.86a2 2 0 0 0-3.42 0z" />
      <line x1="12" y1="9" x2="12" y2="13" />
      <line x1="12" y1="17" x2="12.01" y2="17" />
    </svg>
  );
}
