import { PitchCard } from "./PitchCard";
import { ShareButton } from "./ShareButton";
import { ScoreBreakdown } from "./ScoreBreakdown";
import { CreditsCard } from "./CreditsCard";
import { LyricTranslationCard } from "./LyricTranslationCard";
import { BrandDNACard } from "./BrandDNACard";
import { GeoInfluenceCard } from "./GeoInfluenceCard";
import { DemographicsCard } from "./DemographicsCard";
import { CampaignBanner } from "./CampaignBanner";
import { MegaphoneIcon } from "./icons";
import type { SavedReport } from "@/lib/types";

/**
 * The Pitch surface for a single report. Holds EVERYTHING the report does — the
 * pitch card, full score breakdown, credits, lyric context, brand DNA, the
 * worldwide-influence map and the audience demographics — plus a campaign banner
 * and the public-share action.
 */
export function PitchView({ report }: { report: SavedReport }) {
  return (
    <div className="space-y-5">
      <div className="sf-card sf-card-pad flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
        <div className="flex items-center gap-3">
          <span className="inline-flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-purple-600/20 ring-1 ring-inset ring-purple-500/30">
            <MegaphoneIcon className="h-5 w-5 text-lime-400" aria-hidden />
          </span>
          <div className="min-w-0">
            <h2 className="truncate text-base font-semibold text-white">
              Pitch “{report.track.title}”
            </h2>
            <p className="text-xs text-soft">
              The full pitch — score, breakdown, credits, audience &amp; map — plus a
              public link anyone can open.
            </p>
          </div>
        </div>
        <ShareButton
          shareEndpoint={`/api/reports/${report.id}/share`}
          sharePrefix="/share/"
          initialToken={report.shareToken}
          label="Pitch"
        />
      </div>

      {/* Campaign banner (generated by Higgsfield) */}
      <CampaignBanner
        bannerUrl={report.bannerUrl}
        title={report.name?.trim() || report.track.title}
        subtitle={report.brief.brief}
      />

      <PitchCard report={report} />

      {/* Full score breakdown — same 7-factor model as the report. */}
      <div className="sf-card sf-card-pad">
        <h3 className="mb-4 text-sm font-semibold text-white">Score breakdown</h3>
        <ScoreBreakdown breakdown={report.analysis.breakdown} />
      </div>

      {/* Credits (MusicBrainz) */}
      <CreditsCard credits={report.track.credits} />

      {/* Lyric context + brand DNA — short context only, fetched live. */}
      <LyricTranslationCard
        trackId={report.track.trackId}
        brief={report.brief.brief}
      />
      <BrandDNACard
        trackId={report.track.trackId}
        title={report.track.title}
        artist={report.track.artist}
      />

      {/* Worldwide influence + audience demographics */}
      <GeoInfluenceCard
        title={report.track.title}
        artist={report.track.artist}
        language={report.track.language}
        genre={report.track.genre}
      />
      <DemographicsCard
        title={report.track.title}
        artist={report.track.artist}
        language={report.track.language}
        genre={report.track.genre}
      />
    </div>
  );
}
